title = "Adelblog"

base_url = "https://www.adelbertc.com/"

generate_feed = true

compile_sass = true

highlight_code = true

build_search_index = false

theme = "anpu"

taxonomies = [
    { name = "tags" },
]

[extra]
anpu_menu_links = [
    { url = "$BASE_URL", name = "Home" },
    { url = "$BASE_URL/about", name = "About" },
    { url = "$BASE_URL/assets/adelbertchang_resume.pdf", name = "Resume" },
    { url = "$BASE_URL/publications", name = "Publications" },
    { url = "$BASE_URL/tags", name = "Tags" },
    { url = "$BASE_URL/atom.xml", name = "Atom" },
]

anpu_date_format = "%e %B %Y"
