#!/usr/bin/env bash

set -eu

# Temporarily store uncommited changes
git stash

# Verify correct branch
git checkout develop

# Build new files
nix-build

# Get previous files
git fetch --all
git checkout -b master --track origin/master

# Overwrite existing files with new files
cp -a result/. .

# /nix/store files are owned by root, chown them
# back to my user so that say, Git, doesn't freak out
my_user=$(whoami)
chown -R ${my_user} .
chmod -R 744 .

# Commit
git add -A
git commit -m "publish $(date -u)"

# Verify
git diff HEAD^1
echo "Verify your changes before pushing!"
echo "If something is wrong, return to original state by running:"
echo "git checkout develop"
echo "git branch -D master"
echo "git stash pop"
